### ISSUE TITLE
Status wird immer als online (1) angezeigt.

### ISSUE THREAD

**Issue by 2radfahrer** [Gagi2k/LoxBerry-Plugin-WifiScanner#1]
2018-02-20 21:03:03 : INFO: Checking devices from User: iPad
2018-02-20 21:03:04 : INFO: Mac x:xx:xx:xx:xx:xx (iPad) is online with IP 192.168.2.24 on 802.11
2018-02-20 21:03:04 : INFO: Using LoxoneMiniserver at 192.168.2.100.
2018-02-20 21:03:04 : INFO: Sending Data 'iPad:1' to LoxoneMiniserver. IP:192.168.2.100 Port:7007

Ich benutze eine Fritzbox 7490 und einen Repeater 1750E.
Unabhängig davon ob ich das Gerät per WLAN mit der Fritzbox oder mit dem Repeater verbinde ändert sich sich Onlinestatus auch in der Logdatei nicht.

**Comment by Gagi2k** [comment]
Hi,

solange das iPad im Netzwerk verbunden ist, unabhaengig davon ob mit Repeater oder FritzBox sollte der Status auch online (1) bleiben. Sobald du das iPad in den Flugmodus vesetzt sollte es nach ein paar minuten auf offline (0) gehen. Die Zeit zwischen iPad Flugmodus und dass erkennen dass das iPad wirklich offline ist, kann ich leider nicht beeinflussen, dass kann manchmal ein paar Minuten dauern. In Zukunft ist es geplant das aktiv abzufragen, womit man schneller Feedback bekommen sollte.

**Comment by 2radfahrer** [comment]
Danke für die schnelle Antwort!
Ich habe aber dummerweise vergessen zu erwähnen daß das iPad auch außerhalb des WLANs den gleichen Status behält. Und das auch über mehrere Stunden.
Mit zwei weiteren iPhones habe ich das gleiche Problem.
Ich habe mittlerweile die Frage auch ins Forum gestellt.

**Comment by Gagi2k** [comment]
Ich glaube wir können den Bug schliesen, nachdem es ein Fehler in der FritzBox war ?

**Comment by Gagi2k** [comment]
Ich glaube wir können den Bug schliesen, nachdem es ein Fehler in der FritzBox war ?
