### ISSUE TITLE
MQTT Abfrage

### ISSUE THREAD

**Issue by christianTF** [Gagi2k/LoxBerry-Plugin-WifiScanner#7]
https://github.com/Gagi2k/LoxBerry-Plugin-WifiScanner/blob/5812a9889d2f7199111c6338b7cf34168ecfa689/webfrontend/htmlauth/index.cgi#L193

Das hier wäre sicherer:
https://www.loxwiki.eu/display/LOXBERRY/LoxBerry%3A%3AIO%3A%3Amqtt_connectiondetails

```
eval {
require LoxBerry::IO;
my $mqttcred = LoxBerry::IO::mqtt_connectiondetails();
If ( ! $mqttcred ) {
   Print "MQTT not installed";
}
};
```

**Comment by Gagi2k** [comment]
Wollte zwar eigentlich die versionsabfrage fixen, aber das schaut noch besser aus, danke!

**Comment by christianTF** [comment]
Mit dem Eval fängst du eine Exception ab, wenn es die Funktion noch nicht gibt. Dann geht der Code auch mit LB<2. 
Du initialisierst deine Variable vorher mit 0 (kein MQTT), und in diesem if setzt du sie 1.
Wenn MQTT nicht drauf ist, oder gar die Funktion noch garnicht existiert, bleibt deine Variable 0 und du disablst damit den Schalter.

**Comment by Gagi2k** [comment]
Sollte im pre-release gefixed sein

**Comment by Gagi2k** [comment]
Fixed in WifiScanner Release 2.2
