### ISSUE TITLE
Only upgrade state of the first user

### ISSUE THREAD

**Issue by madito** [Gagi2k/LoxBerry-Plugin-WifiScanner#9]
Hi!

Only upgrade the state of the first user;

21:25:03.736 OK: Sending Data 'wifiscanner/USER1/1' to MQTT broker localhost:1883
21:25:03.747 OK: Sending Data 'wifiscanner/USER2/0' to MQTT broker localhost:1883

![image](https://user-images.githubusercontent.com/5938785/95663407-53b2bd00-0b3f-11eb-8679-657c5cc5b625.png)

**Comment by Gagi2k** [comment]
Please provide more details, e.g. logs or what's actually wrong.

**Comment by madito** [comment]
I do not provide more information, the verification process seems to detect it well, you can see that the information of both users is "sent to the MQTT", but only the first one is updated, I have reversed the order of users and only user 1 is updated

I used pre-released 2.2

**Comment by Gagi2k** [comment]
The log message seems to be correct and this is what i'm sending to the broker:

`     LOGOK "Sending Data 'wifiscanner/$users[$j]{NAME}/$users[$j]{ONLINE}' to MQTT broker $mqttcred->{brokeraddress}";
       $mqtt->retain("wifiscanner/".$users[$j]{NAME}, $users[$j]{ONLINE}) or lox_die "Send error: $!";`

**Comment by madito** [comment]
Hi!

The broker dont received the second user, I can only see;

22:02:23.225 INFO: MQTT received: wifiscanner/User1: 0
22:02:23.225 wifiscanner/User1 is cached
22:02:23.226 HTTP: Preparing input wifiscanner_User1 (using cache): 0

The log:

22:01:31.556 OK: Sending Data 'wifiscanner/User1/0' to MQTT broker localhost:1883
22:01:31.567 OK: Sending Data 'wifiscanner/User2/0' to MQTT broker localhost:1883

All version:

Loxberry v2.2.0
MQTT Gateway v1.1.2
Wifi Scanner V2.2

**Comment by Gagi2k** [comment]
As this is fixed in the latest Loxberry pre-release i guess we can close this ?

**Comment by Gagi2k** [comment]
Fixed in Loxberry Pre-Release v2.2.0.1
